# -*- coding: utf-8 -*-
"""EXOSUIT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xz64LHb-U65HXr_rUtTEsUacYWskAvNc
"""

!ls

import pandas as pd
df = pd.read_csv("motor_mapping_extended.csv")
df

SPINE_LIMITS = {
    "spine_mid": (-12, 12),
    "spine_lower": (-10, 10)
}

def spine_safe(joint, angle):
    if joint not in SPINE_LIMITS:
        return True
    low, high = SPINE_LIMITS[joint]
    return low <= angle <= high

# quick check
spine_safe("spine_mid", 5), spine_safe("spine_mid", 20)

mapping = df.set_index("intent").to_dict(orient="index")

def generate_command(intent):
    if intent not in mapping:
        return {"status": "UNKNOWN"}

    row = mapping[intent]
    joint = row["joint_name"]
    angle = row["angle_max_deg"]

    if not spine_safe(joint, angle):
        return {
            "status": "UNSAFE",
            "joint": joint,
            "safe_angle": 0
        }

    return {
        "status": "SAFE",
        "joint": joint,
        "target_angle": angle
    }

generate_command("spine_micro_flex")

!mkdir -p logger logs
!touch logger/__init__.py

!ls

# Commented out IPython magic to ensure Python compatibility.
# %%writefile logger/unified_logger.py
# import csv
# import time
# import os
# 
# LOG_DIR = "logs"
# LOG_FILE = os.path.join(LOG_DIR, "exosuit_alpha_log.csv")
# 
# def init_logger():
#     os.makedirs(LOG_DIR, exist_ok=True)
#     if not os.path.exists(LOG_FILE):
#         with open(LOG_FILE, "w", newline="") as f:
#             writer = csv.writer(f)
#             writer.writerow([
#                 "timestamp",
#                 "gesture",
#                 "intent",
#                 "motorcmd_id",
#                 "angle",
#                 "safety_flag",
#                 "haptic_flag"
#             ])
# 
# def log_event(gesture, intent, motorcmd_id, angle, safety_flag, haptic_flag):
#     with open(LOG_FILE, "a", newline="") as f:
#         writer = csv.writer(f)
#         writer.writerow([
#             time.time(),
#             gesture,
#             intent,
#             motorcmd_id,
#             angle,
#             safety_flag,
#             haptic_flag
#         ])
#

from logger.unified_logger import init_logger, log_event

init_logger()
log_event("test", "test_intent", "motor_x", 5, "SAFE", "OFF")

import pandas as pd
pd.read_csv("logs/exosuit_alpha_log.csv")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_exosuit_alpha.py
# import pandas as pd
# from logger.unified_logger import init_logger, log_event
# 
# df = pd.read_csv("motor_mapping_extended.csv")
# mapping = df.set_index("intent").to_dict(orient="index")
# 
# SPINE_LIMITS = {
#     "spine_mid": (-12, 12),
#     "spine_lower": (-10, 10)
# }
# 
# SAFE_POSE = {
#     "spine_mid": 0,
#     "spine_lower": 0,
#     "hand_joint": 0,
#     "ankle_joint": 0
# }
# 
# def spine_safe(joint, angle):
#     if joint not in SPINE_LIMITS:
#         return True
#     low, high = SPINE_LIMITS[joint]
#     return low <= angle <= high
# 
# def execute_command(gesture, intent):
#     row = mapping[intent]
#     motorcmd_id = row["motorcmd_id"]
#     joint = row["joint_name"]
#     angle = row["angle_max_deg"]
# 
#     if not spine_safe(joint, angle):
#         log_event(gesture, intent, motorcmd_id, angle, "UNSAFE", "ON")
#         print("⚠️ UNSAFE → SAFE POSE")
#         return SAFE_POSE
# 
#     log_event(gesture, intent, motorcmd_id, angle, "SAFE", "OFF")
#     print(f"✅ MOVE {joint} → {angle}°")
#     return {joint: angle}
# 
# if __name__ == "__main__":
#     init_logger()
#     demo_sequence = [
#         ("fist", "hand_close"),
#         ("open", "hand_open"),
#         ("step", "foot_step"),
#         ("lean_fwd", "spine_flex"),
#         ("micro_lean_fwd", "spine_micro_flex"),
#         ("brace", "spine_lock")
#     ]
# 
#     for g, i in demo_sequence:
#         execute_command(g, i)
#

!python run_exosuit_alpha.py

pd.read_csv("logs/exosuit_alpha_log.csv")